package lotr.common.entity.npc;

import lotr.common.LOTRMod;
import lotr.common.entity.animal.*;

public class LOTRUnitTradeEntries {
public static LOTRUnitTradeEntries RED_DWARF_COMMANDER = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityRedDwarfWarrior.class, 200, 0.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityRedDwarfAxeThrower.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityRedDwarfWarrior.class, LOTREntityWildBoar.class, "RedDwarfWarrior_Boar", 500, 150.0f).setMountArmor(LOTRMod.boar_armor_red_dwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityRedDwarfAxeThrower.class, LOTREntityWildBoar.class, "RedDwarfAxeThrower_Boar", 700, 200.0f).setMountArmor(LOTRMod.boar_armor_red_dwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityRedDwarfBannerBearer.class, 500, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
public static LOTRUnitTradeEntries WIND_DWARF_COMMANDER = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityWindDwarfWarrior.class, 200, 0.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfAxeThrower.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfWarrior.class, LOTREntityWildBoar.class, "WindDwarfWarrior_Boar", 500, 150.0f).setMountArmor(LOTRMod.boar_armor_wind_dwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfAxeThrower.class, LOTREntityWildBoar.class, "WindDwarfAxeThrower_Boar", 700, 200.0f).setMountArmor(LOTRMod.boar_armor_wind_dwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfBannerBearer.class, 500, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));

public static LOTRUnitTradeEntries DARK_WOOD_CAPTAIN = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityDarkWoodElf.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityDarkWoodSoldierElf.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityDarkWoodSoldierElf.class, LOTREntityHorse.class, "DarkWoodWarrior_Horse", 700, 200.0f).setMountArmor(LOTRMod.horseArmorDarkWood).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityDarkWoodBannerBearer.class, 700, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
public static LOTRUnitTradeEntries NUMENOR_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityNumenorSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityNumenorArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityNumenorSoldier.class, LOTREntityHorse.class, "NumenorSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorNumenor).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityNumenorBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries KHAND_WARLORD = new LOTRUnitTradeEntries(200.0f,  new LOTRUnitTradeEntry(LOTREntityKhandSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityKhandArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityKhandSoldier.class, LOTREntityHorse.class, "KhandSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorKhand).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityKhandBannerBearer.class, 500, 200.0f));

public static LOTRUnitTradeEntries MORDOR_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcBombardier.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityMordorWarg.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, LOTREntityMordorWarg.class, "MordorOrc_Warg", 400, 100.0f).setMountArmor(LOTRMod.wargArmorMordor, 0.5f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, LOTREntityMordorWarg.class, "MordorOrcArcher_Warg", 600, 150.0f).setMountArmor(LOTRMod.wargArmorMordor, 0.5f), new LOTRUnitTradeEntry(LOTREntityMordorWargBombardier.class, 500, 250.0f), new LOTRUnitTradeEntry(LOTREntityOlogHai.class, 1200, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityMordorBannerBearer.class, 400, 150.0f), new LOTRUnitTradeEntry(LOTREntityMinasMorgulBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries GONDORIAN_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityGondorArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, LOTREntityHorse.class, "GondorSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityGondorTowerGuard.class, 500, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGondorBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries DWARF_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityDwarf.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityDwarfWarrior.class, 300, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfAxeThrower.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 500, 150.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfAxeThrower.class, LOTREntityWildBoar.class, "DwarfAxeThrower_Boar", 700, 200.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfBannerBearer.class, 500, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
public static LOTRUnitTradeEntries URUK_HAI_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityIsengardSnaga.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityIsengardSnagaArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityUrukHai.class, 400, 0.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiCrossbower.class, 600, 50.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiSapper.class, 700, 100.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiBerserker.class, 600, 150.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityUrukWarg.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityIsengardSnaga.class, LOTREntityUrukWarg.class, "IsengardSnaga_Warg", 400, 100.0f).setMountArmor(LOTRMod.wargArmorUruk, 0.5f), new LOTRUnitTradeEntry(LOTREntityIsengardSnagaArcher.class, LOTREntityUrukWarg.class, "IsengardSnagaArcher_Warg", 600, 150.0f).setMountArmor(LOTRMod.wargArmorUruk, 0.5f), new LOTRUnitTradeEntry(LOTREntityUrukWargBombardier.class, 500, 250.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiBannerBearer.class, 60, 150.0f));
public static LOTRUnitTradeEntries ELF_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityGaladhrimElf.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarden.class, 400, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarrior.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarrior.class, LOTREntityHorse.class, "GaladhrimWarrior_Horse", 700, 200.0f).setMountArmor(LOTRMod.horseArmorGaladhrim).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimBannerBearer.class, 700, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
public static LOTRUnitTradeEntries ROHIRRIM_MARSHAL = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityRohirrimWarrior.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityRohirrimArcher.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntityRohirrimWarrior.class, LOTREntityHorse.class, "Rohirrim_Horse", 500, 100.0f).setMountArmor(LOTRMod.horseArmorRohan), new LOTRUnitTradeEntry(LOTREntityRohirrimArcher.class, LOTREntityHorse.class, "RohirrimArcher_Horse", 700, 150.0f).setMountArmor(LOTRMod.horseArmorRohan), new LOTRUnitTradeEntry(LOTREntityRohanBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries HOBBIT_SHIRRIFF_CHIEF = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityHobbitShirriff.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityHobbitShirriff.class, LOTREntityShirePony.class, "HobbitShirriff_Pony", 400, 50.0f));
public static LOTRUnitTradeEntries DUNLENDING_WARLORD = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityDunlending.class, 150, 0.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingWarrior.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingAxeThrower.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingBerserker.class, 500, 200.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDunlendingBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries WOOD_ELF_CAPTAIN = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityWoodElf.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityWoodElfScout.class, 400, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfWarrior.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfWarrior.class, LOTREntityElk.class, "WoodElfWarrior_Elk", 700, 200.0f).setMountArmor(LOTRMod.elkArmorWoodElven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
public static LOTRUnitTradeEntries ANGMAR_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityAngmarOrc.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcBombardier.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarWarg.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrc.class, LOTREntityAngmarWarg.class, "AngmarOrc_Warg", 400, 100.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.5f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcArcher.class, LOTREntityAngmarWarg.class, "AngmarOrcArcher_Warg", 600, 150.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.5f), new LOTRUnitTradeEntry(LOTREntityAngmarWargBombardier.class, 500, 250.0f), new LOTRUnitTradeEntry(LOTREntityTroll.class, 1000, 250.0f), new LOTRUnitTradeEntry(LOTREntityMountainTroll.class, 120, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngmarBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries MORDOR_ORC_SLAVER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityNurnSlave.class, 400, 0.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries MORDOR_ORC_SPIDER_KEEPER = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityMordorSpider.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, 400, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, LOTREntityMordorSpider.class, "MordorOrc_Spider", 500, 50.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, LOTREntityMordorSpider.class, "MordorOrcArcher_Spider", 700, 100.0f), new LOTRUnitTradeEntry(LOTREntityNanUngolBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries GUNDABAD_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityGundabadOrc.class, 150, 0.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrcArcher.class, 350, 50.0f), new LOTRUnitTradeEntry(LOTREntityGundabadWarg.class, 200, 50.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrc.class, LOTREntityGundabadWarg.class, "GundabadOrc_Warg", 350, 100.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrcArcher.class, LOTREntityGundabadWarg.class, "GundabadOrcArcher_Warg", 550, 150.0f), new LOTRUnitTradeEntry(LOTREntityGundabadUruk.class, 400, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGundabadUrukArcher.class, 600, 300.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGundabadBannerBearer.class, 350, 150.0f)); 
public static LOTRUnitTradeEntries RANGER_NORTH_CAPTAIN = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRangerNorth.class, 500, 0.0f), new LOTRUnitTradeEntry(LOTREntityRangerNorth.class, LOTREntityHorse.class, "RangerNorth_Horse", 700, 100.0f), new LOTRUnitTradeEntry(LOTREntityRangerNorthBannerBearer.class, 700, 150.0f));
public static LOTRUnitTradeEntries HOBBIT_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHobbitFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries HIGH_ELF_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityHighElf.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityHighElfWarrior.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityHighElfWarrior.class, LOTREntityHorse.class, "HighElfWarrior_Horse", 700, 200.0f).setMountArmor(LOTRMod.horseArmorHighElven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityHighElfBannerBearer.class, 700, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
public static LOTRUnitTradeEntries NEAR_HARADRIM_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityNearHaradrimWarrior.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityNearHaradrimArcher.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntitySouthronChampion.class, LOTREntityHorse.class, "SouthronChampion_Horse", 600, 100.0f).setMountArmor(LOTRMod.horseArmorNearHarad).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityNearHaradBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries BLUE_DWARF_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityBlueDwarf.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityBlueDwarfWarrior.class, 300, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfAxeThrower.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfWarrior.class, LOTREntityWildBoar.class, "BlueDwarfWarrior_Boar", 500, 150.0f).setMountArmor(LOTRMod.boarArmorBlueDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfAxeThrower.class, LOTREntityWildBoar.class, "BlueDwarfAxeThrower_Boar", 700, 200.0f).setMountArmor(LOTRMod.boarArmorBlueDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfBannerBearer.class, 500, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
public static LOTRUnitTradeEntries DOL_GULDUR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityDolGuldurOrc.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrcArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityMirkwoodSpider.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrc.class, LOTREntityMirkwoodSpider.class, "DolGuldurOrc_Spider", 400, 100.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrcArcher.class, LOTREntityMirkwoodSpider.class, "DolGuldurOrcArcher_Spider", 600, 150.0f), new LOTRUnitTradeEntry(LOTREntityMirkTroll.class, 1000, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolGuldurBannerBearer.class, 400, 0.0f));
public static LOTRUnitTradeEntries RANGER_ITHILIEN_CAPTAIN = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRangerIthilien.class, 500, 0.0f), new LOTRUnitTradeEntry(LOTREntityRangerIthilienBannerBearer.class, 700, 150.0f));
public static LOTRUnitTradeEntries HALF_TROLL_WARLORD = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityHalfTroll.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityHalfTrollWarrior.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityHalfTrollWarrior.class, LOTREntityRhino.class, "HalfTrollWarrior_Rhino", 700, 200.0f).setMountArmor(LOTRMod.rhinoArmorHalfTroll, 0.5f), new LOTRUnitTradeEntry(LOTREntityHalfTrollBannerBearer.class, 700, 150.0f));
public static LOTRUnitTradeEntries DOL_AMROTH_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityDolAmrothSoldier.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolAmrothArcher.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntitySwanKnight.class, 500, 100.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolAmrothSoldier.class, LOTREntityHorse.class, "DolAmrothSoldier_Horse", 500, 100.0f).setMountArmor(LOTRMod.horseArmorDolAmroth, 0.5f), new LOTRUnitTradeEntry(LOTREntitySwanKnight.class, LOTREntityHorse.class, "SwanKnight_Horse", 700, 200.0f).setMountArmor(LOTRMod.horseArmorDolAmroth).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolAmrothBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries MOREDAIN_CHIEFTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityMoredainWarrior.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityMoredainWarrior.class, LOTREntityZebra.class, "MoredainWarrior_Zebra", 400, 100.0f), new LOTRUnitTradeEntry(LOTREntityMoredainBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries ANGMAR_HILLMAN_CHIEFTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityAngmarHillman.class, 150, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanWarrior.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanAxeThrower.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillman.class, LOTREntityAngmarWarg.class, "AngmarHillman_Warg", 350, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanWarrior.class, LOTREntityAngmarWarg.class, "AngmarHillmanWarrior_Warg", 500, 150.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.3f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanAxeThrower.class, LOTREntityAngmarWarg.class, "AngmarHillmanAxeThrower_Warg", 700, 200.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.3f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries TAUREDAIN_CHIEFTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityTauredainWarrior.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityTauredainBlowgunner.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntityTauredainBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries TAUREDAIN_FARMER = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityTauredainFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries DALE_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityDaleLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityDaleSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityDaleArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityDaleSoldier.class, LOTREntityHorse.class, "DaleSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorDale), new LOTRUnitTradeEntry(LOTREntityDaleBannerBearer.class, 500, 200.0f), new LOTRUnitTradeEntry(LOTREntityEsgarothBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries DORWINION_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionGuard.class, 400, 0.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionCrossbower.class, 600, 50.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionBannerBearer.class, 600, 150.0f));
public static LOTRUnitTradeEntries DORWINION_ELF_CAPTAIN = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionElfWarrior.class, 500, 0.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionElfArcher.class, 700, 50.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionElfBannerBearer.class, 700, 150.0f));
public static LOTRUnitTradeEntries DORWINION_VINEKEEPER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionVinehand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries LOSSARNACH_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityLossarnachAxeman.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityLossarnachBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries PELARGIR_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityLebenninLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityPelargirMarine.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityPelargirBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries PINNATH_GELIN_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityPinnathGelinSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityPinnathGelinSoldier.class, LOTREntityHorse.class, "PinnathGelinSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityPinnathGelinBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries BLACKROOT_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootSoldier.class, LOTREntityHorse.class, "BlackrootSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityBlackrootBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries GONDOR_FARMER = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityGondorFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries NUMENOR_FARMER = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityNumenorFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));

public static LOTRUnitTradeEntries LEBENNIN_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityLebenninLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityGondorArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityLebenninBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries LAMEDON_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityLamedonHillman.class, 150, 0.0f), new LOTRUnitTradeEntry(LOTREntityLamedonSoldier.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityLamedonArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityLamedonSoldier.class, LOTREntityHorse.class, "LamedonSoldier_Horse", 500, 150.0f).setMountArmor(LOTRMod.horseArmorLamedon), new LOTRUnitTradeEntry(LOTREntityLamedonBannerBearer.class, 500, 200.0f));
public static LOTRUnitTradeEntries ROHAN_FARMER = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityRohanFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries EASTERLING_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityEasterlingLevyman.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingWarrior.class, 300, 50.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingArcher.class, 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingGoldWarrior.class, 500, 200.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityEasterlingWarrior.class, LOTREntityHorse.class, "EasterlingWarrior_Horse", 500, 150.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingArcher.class, LOTREntityHorse.class, "EasterlingArcher_Horse", 70, 200.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingGoldWarrior.class, LOTREntityHorse.class, "EasterlingGoldWarrior_Horse", 70, 300.0f).setMountArmor(LOTRMod.horseArmorRhunGold).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityEasterlingFireThrower.class, 60, 150.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingBannerBearer.class, 50, 200.0f));
public static LOTRUnitTradeEntries EASTERLING_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityEasterlingFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries RIVENDELL_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRivendellElf.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityRivendellWarrior.class, 500, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityRivendellWarrior.class, LOTREntityHorse.class, "RivendellWarrior_Horse", 700, 200.0f).setMountArmor(LOTRMod.horseArmorRivendell).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityRivendellBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
public static LOTRUnitTradeEntries HARNEDOR_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityHarnedorWarrior.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorWarrior.class, LOTREntityHorse.class, "HarnedorWarrior_Horse", 400, 100.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorArcher.class, LOTREntityHorse.class, "HarnedorArcher_Horse", 600, 150.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries UMBAR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityUmbarWarrior.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityUmbarArcher.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntityUmbarWarrior.class, LOTREntityHorse.class, "UmbarWarrior_Horse", 500, 100.0f).setMountArmor(LOTRMod.horseArmorUmbar), new LOTRUnitTradeEntry(LOTREntityUmbarBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries CORSAIR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityCorsair.class, 200, 0.0f).setExtraInfo("Corsair"));
public static LOTRUnitTradeEntries NOMAD_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityNomadWarrior.class, 200, 0.0f), new LOTRUnitTradeEntry(LOTREntityNomadArcher.class, 400, 50.0f), new LOTRUnitTradeEntry(LOTREntityNomadWarrior.class, LOTREntityCamel.class, "NomadWarrior_Camel", 400, 100.0f), new LOTRUnitTradeEntry(LOTREntityNomadArcher.class, LOTREntityCamel.class, "NomadArcher_Camel", 600, 150.0f), new LOTRUnitTradeEntry(LOTREntityNomadBannerBearer.class, 400, 150.0f));
public static LOTRUnitTradeEntries GULF_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGulfHaradWarrior.class, 300, 0.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradArcher.class, 500, 50.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradWarrior.class, LOTREntityHorse.class, "GulfWarrior_Horse", 500, 100.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradArcher.class, LOTREntityHorse.class, "GulfArcher_Horse", 700, 150.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradBannerBearer.class, 500, 150.0f));
public static LOTRUnitTradeEntries CORSAIR_SLAVER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHaradSlave.class, 400, 0.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries HARNEDOR_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHarnedorFarmhand.class, 400, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
public static LOTRUnitTradeEntries BLACK_URUK_CAPTAIN = new LOTRUnitTradeEntries(400.0f, new LOTRUnitTradeEntry(LOTREntityBlackUruk.class, 600, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBlackUrukArcher.class, 800, 300.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityOlogHai.class, 1200, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBlackUrukBannerBearer.class, 800, 400.0f).setPledgeExclusive());
public LOTRUnitTradeEntry[] tradeEntries;
public static final int MOREDAIN_MERCENARY_COST = 200;


    public LOTRUnitTradeEntries(float baseAlignment, LOTRUnitTradeEntry... trades) {
        for(LOTRUnitTradeEntry trade : this.tradeEntries = trades) {
            trade.alignmentRequired += baseAlignment;
            if(!(trade.alignmentRequired < 0.0f)) continue;
            throw new IllegalArgumentException("Units cannot require negative alignment!");
        }
    }
}
